### ISSUE TITLE
Fails to initialize with MKR WI-FI 1010 and MKR IOT CARRIER 

### ISSUE THREAD

**Issue by SergioSerrao** [arduino-libraries/MKRIMU#21]
The example code Fails to initialize with MKR WI-FI 1010 and MKR IOT CARRIER that uses the LSM6DSOX IMU

**Comment by per1234** [comment]
Hi @SergioSerrao. This library is for use with the [**Arduino MKR IMU Shield**](https://docs.arduino.cc/hardware/mkr-imu-shield). You should instead use the "**Arduino_MKRIoTCarrier**" library with your [**Arduino MKR IoT Carrier**](https://docs.arduino.cc/hardware/mkr-iot-carrier).

If you have any questions or problems, you are welcome to post on Arduino Forum:

https://forum.arduino.cc/

I'm sure we'll be able to help you out over there.

Regards,
Per

**Comment by SergioSerrao** [comment]
I tried the IMU library for the MKR IOT carrier, but it's useless, I need
the heading, roll and pitch values not the raw values from the sensors. I
might give a go and add a kalman filter or Euler, but it's not one easy
task.
